### ISSUE TITLE
IndexError: too many indices error when running bootstrap.py

### ISSUE THREAD

**Issue by phongnhhn92** [Arsey/keras-transfer-learning-for-oxford102#11]
I have this error at line 
move_files('train', labels[idx_test, :])
Index Error: too many indices
Any solution for this ? Thanks !

**Comment by Arsey** [comment]
Strange error. I didn't get it. Try again from scratch (by deleting the **data** dir), as I did some improvements in the code (don't forget to **git pull** before).

**Comment by djones4487169** [comment]
I get the same error - was this sorted out?

**Comment by cottontail7** [comment]
switching from python3.5 to python2.7 solved this problem for me

**Comment by djones4487169** [comment]
Any ideas how I can solve this problem sticking with Python3.5 which I need
for some other scripts?

**Comment by djones4487169** [comment]
Alternatively, if I have a cats and dogs data set with the following data structure:

data/
    train/
        dogs/
            dog001.jpg
            dog002.jpg
            ...
        cats/
            cat001.jpg
            cat002.jpg
            ...
    validation/
        dogs/
            dog001.jpg
            dog002.jpg
            ...
        cats/
            cat001.jpg
            cat002.jpg

How can I change the code to get this data to work?

**Comment by djones4487169** [comment]
I have the following data structure cats (120, class=0) and dogs (120, class=1):

data/sorted/test/0
data/sorted/test/1

data/sorted/train/0
data/sorted/train/1

data/sorted/valid/0
data/sorted/valid/1

The bottleneck routine runs and stores the .npy files OK. I get an error message when running the train_top_model() and I have been through debugging got correct train and validation numbers and cannot see why I'm getting this error. Please help.

Error message says more training samples (7,200) than target labels (240)?? where 7200 comes from I have no idea?

**Comment by jszym** [comment]
In python 3.6, the `zip` function returns a Zip object which returns elements on it's `__next__()` method (I haven't looked up the behaviour in earlier versions).

I resolved this in 3.6 with a simple list comprehension:

```python
labels = np.array([i for i in zip(files, image_labels)])
```

**Comment by shirishr** [comment]
@jszym, Thanks man. I followed your lead for Python 3.5 and it worked like a charm.
