### ISSUE TITLE
Dataset directory's structure

### ISSUE THREAD

**Issue by DeepStillWater** [Arsey/keras-transfer-learning-for-oxford102#16]
I wants to train my own datasets about 100 classes ,so I want to know the structures of datasets,and some other guide,Thanks!

**Comment by Arsey** [comment]
@DeepStillWater you can have as many classes as you need. For the structure just follow by the *data/sorted* dir structure after running the bootstrap.py

**Comment by DeepStillWater** [comment]
Oh,thanks

 I have got it.The data strucure like this:

data/

        sorted/
                train/
                        class1/
                                 picture1.jpg
                                 ...
                        class2/
                                picture1.jpg
                                ...
                         ...
                valid/
                        class1/
                                picturex.jpg
                                 ...
                         class2/
                                picturex.jpg
                                ...
                          ...

**Comment by Arsey** [comment]
correct

**Comment by Arsey** [comment]
data structure description is added to README
