### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by webschik** [Arsey/keras-transfer-learning-for-oxford102#24]
Hi, Alex

First of all, thank you for your work and for sharing with us! :)

I found that this repo contained the link to pre-trained models
https://github.com/Arsey/keras-transfer-learning-for-oxford102/pull/23/files#diff-c9bfeb27d1153a74dbaec8124d755317 by @indiejoseph.

Unfortunately, they are not available now. Is it possible to download somewhere pre-trained models, classes, etc. (`/trained` folder)? 
Because without a good hardware `train.py` takes a lot of time. Would be great to skip the [step 2](https://github.com/Arsey/keras-transfer-learning-for-oxford102#step-2-train)

Thank you!

**Comment by Arsey** [comment]
Keras should do it for you. When you run to train for the first time, Keras'es implementation of ResNet50 will download pre-trained weights.

**Comment by webschik** [comment]
@Arsey, thank you! I will check that
