### ISSUE TITLE
AttributeError: 'module' object has no attribute 'save_bottleneck_features'

### ISSUE THREAD

**Issue by jshchengcong** [Arsey/keras-transfer-learning-for-oxford102#3]
when I run the file train.py, it turns out the problem like above.
and I have searched online for answers but no useful ones.
So I wonder if you can help me with it.
Thanks a lot!

**Comment by Arsey** [comment]
@jshchengcong I just did a fix - https://github.com/Arsey/keras-transfer-learning-for-oxford102/commit/9b3086aa442e9af65133d11e7c5c66b67b27ce1a. The reason can be related with pandas that also have submodule called 'bottleneck'

**Comment by jshchengcong** [comment]
Thanks!
