### ISSUE TITLE
Can we transfer learning for any generic image set with multiple classes

### ISSUE THREAD

**Issue by debarko** [Arsey/keras-transfer-learning-for-oxford102#5]
Hi,

This works awesome for oxford102 flowers DB, but if you can modify this for working on any DB with proper structured imageset then it become super awesome.

Would really love to know your views on that. If you don't have time, then you can let me know the steps and I can give a PR for this.

**Comment by Arsey** [comment]
@debarko actually it supports any DB. just follow the structure in data/sorted and then on running train.py set proper values for parameters --train_dir and --valid_dir
